- name: Start EC2 Instances
  hosts: localhost
  gather_facts: false
  vars:
    region: us-east-1
    instance_ids: "i-0c72fd86e2f38873f"
    access_key: AKIAUO6DBZHSG7JOF4N2
    secret_key: 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
  tasks:
  # - name: start an instance with a public IP address
  #   community.aws.ec2_instance:
  #     name: "public-compute-instance"
  #     key_name: "VPC-kura-useast1"
  #     vpc_subnet_id: subnet-69d6cb24
  #     instance_type: t2.micro
  #     security_group: default
  #     network:
  #       assign_public_ip: true
  #     image_id: ami-083654bd07b5da81d
  #     tags:
  #       Environment: Testing
  #     region: '{{region}}'
  #     aws_access_key: '{{access_key}}'
  #     aws_secret_key: '{{secret_key}}'

  # - name: restart a particular instance by its ID
  #   community.aws.ec2_instance:
  #     state: terminated
  #     instance_ids:
  #       - '{{instance_ids}}'
  #     region: '{{region}}'
  #     aws_access_key: '{{access_key}}'
  #     aws_secret_key: '{{secret_key}}'
  #     wait: yes
  - name: Gather information about all instances
    community.aws.ec2_instance_info:
      region: us-west-2
      access_key: AKIAUO6DBZHSG7JOF4N2
      secret_key: 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
    register: instances
  - debug: var=instances
